# Generated by Django 5.1.7 on 2025-04-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_created_at_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01T00:00:00'),
            preserve_default=False,
        ),
    ]
